### ISSUE TITLE
Nemo 3.6 sidebar not styled

### ISSUE THREAD

**Issue by ponchofiesta** [LinxGem33/OSX-Arc-Darker#22]
In Nemo 3.6 the sidebar is not styled. I did some research to fix main issues but I couldn't find out how to style the scrollbar and parts of the mount usage indicator.

Maybe someone knows how to fix everything else.

# Default behavior with Arc white or plus theme:
![bildschirmfoto von 2018-03-15 15-22-20](https://user-images.githubusercontent.com/12248938/37469062-bd5f5ed6-2864-11e8-9d24-8a34bec5d2bd.png)

# This is my current status:
![bildschirmfoto von 2018-03-15 15-19-48](https://user-images.githubusercontent.com/12248938/37468892-5ac45952-2864-11e8-994c-085e21da9351.png)
![bildschirmfoto von 2018-03-15 15-19-58](https://user-images.githubusercontent.com/12248938/37468899-5c24b102-2864-11e8-8ed1-88425270439b.png)

# Changes made in GTK inspektor:

```css
.nemo-window .sidebar,
.nemo-places-sidebar {
    background-color: #fbfbfb;
}

.nemo-window .sidebar *,
.nemo-places-sidebar .places-treeview {
    color: #5c616c;
}

.nemo-window .sidebar *:hover,
.nemo-places-sidebar .places-treeview:hover {
    background-color: #efeff0;
}

.nemo-window .sidebar *:selected,
.nemo-places-sidebar .places-treeview:selected {
    background-color: #5294e2;
    color: #ffffff;
}

```
